### ISSUE TITLE
{"e":10013,"m":"用户信息已失效,请重新进入页面","d":{"login_url":"https://app.nwu.edu.cn/uc/wap/login?redirect="}}

### ISSUE THREAD

**Issue by qianxliu** [san-qi/NWU_dailyup#1]
{"e":10013,"m":"用户信息已失效,请重新进入页面","d":{"login_url":"https://app.nwu.edu.cn/uc/wap/login?redirect="}}

@san-qi

**Comment by qianxliu** [comment]
学长还是学弟是那一级的……有点厉害，请赐教

**Comment by qianxliu** [comment]
还有离开Debug模式后为什么要等一会儿?

**Comment by san-qi** [comment]
> {"e":10013,"m":"用户信息已失效,请重新进入页面","d":{"login_url":"[https://app.nwu.edu.cn/uc/wap/login?redirect="}}](https://app.nwu.edu.cn/uc/wap/login?redirect=%22%7D%7D)
> 
> @san-qi



> 学长还是学弟是那一级的……有点厉害，请赐教



> 还有离开Debug模式后为什么要等一会儿?


可能是你的学号或者密码信息错了，信息是在data.json这个文件里面改的；不过也有可能是学校服务器的问题，这种情况我经历过，等一段时间就好了。

我18级的，都大三了，挺菜的。

不用Debug的时候是正常模式，因为挂在这个脚本上填报的人挺多的，所以用time库来插入随机时间间隔，免得学校服务器发现异常就让这个程序填报不上了；并且把学号顺序捣乱，让每次填报的时候顺序不一样，这样做只是以防意外而已，可以直接运行Debug那个模式。

**Comment by qianxliu** [comment]
我也是大三的，没想到西北大学还有这等人物，已经Push a request。

**Comment by san-qi** [comment]
> 我也是大三的，没想到西北大学还有这等人物，已经Push a request。

别， 我只是一个混子
感谢提供的修改Pull request， 已合并
